name: betto_inferencing
description: >
  ONNX Runtime inference and embedding models for dense text retrieval.
version: 0.1.0-dev.2
homepage: https://bettongia.github.io/inferencing/
repository: https://github.com/bettongia/inferencing
issue_tracker: https://github.com/bettongia/inferencing/issues

topics:
  - inference
  - embedding
  - onnx

platforms:
  ios:
  android:
  linux:
  macos:
  windows:

environment:
  sdk: ^3.12.0

dependencies:
  betto_lexical: ^0.1.0-dev.1
  betto_onnxrt: ^0.1.0-dev.1
  crypto: ^3.0.7
  path: ^1.9.1

dev_dependencies:
  lints: ^6.1.0
  test: ^1.25.6
